name: exe_test
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.1
  flutter_screenutil: ^5.9.0
  go_router: ^12.0.0
  logger: ^2.0.2
  lottie: ^2.6.0
  path: ^1.8.3
  path_provider: ^2.1.1
  intl: ^0.18.1
  hooks_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  flutter_hooks: ^0.20.3
  fluttertoast: ^8.2.2

  flutter_acrylic: ^1.1.3
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_oss_licenses: ^2.0.1
  riverpod_generator: ^2.3.5
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.3



flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/animation/
    - assets/icons/
    - assets/images/
    - assets/images/logo/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
    - family: Jalnan
      fonts:
        - asset: assets/fonts/Jalnan.ttf
    - family: BMJUA
      fonts:
        - asset: assets/fonts/BMJUA.otf

